name: dask-mpi
dependencies:
  - python=3.8
  - pip:
    - adal==1.2.7
    - adlfs==2023.12.0
    - affine==2.4.0
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - asciitree==0.3.3
    - async-timeout==4.0.3
    - attrs==23.2.0
    - azure-core==1.29.6
    - azure-datalake-store==0.0.53
    - azure-identity==1.15.0
    - azure-keyvault-secrets==4.7.0
    - azure-storage-blob==12.19.0
    - backoff==2.2.1
    - certifi==2023.11.17
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cloudpickle==3.0.0
    - contourpy==1.1.1
    - cryptography==41.0.7
    - dask[complete]==2023.1.0
    - dask-distance==0.2.0
    - dask-geopandas==0.3.1
    - dask-mpi==2022.4.0
    - distributed==2023.1.0
    - entrypoints==0.4
    - fasteners==0.19
    - fiona==1.9.5
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - geojson==3.1.0
    - geopandas==0.13.2
    - HeapDict==1.0.1
    - idna==3.6
    - isodate==0.6.1
    - Jinja2==3.1.3
    - locket==1.0.0
    - markupsafe==2.1.3
    - mpi4py==3.1.5
    - msal==1.26.0
    - msal-extensions==1.1.0
    - msgpack==1.0.7
    - msrest==0.7.1
    - multidict==6.0.4
    - munch==4.0.0
    - numcodecs==0.12.1
    - oauthlib==3.2.2
    - opencensus==0.11.4
    - opencensus.ext.azure==1.1.13
    - opencensus-ext-logging==0.1.1
    - packaging==23.2
    - pandas==1.5.3
    - partd==1.4.1
    - pillow==10.2.0
    - planetary-computer==1.0.0
    - portalocker==2.8.2
    - psutil==5.9.7
    - pyarrow==14.0.2
    - pycparser==2.21
    - pydantic==2.5.3
    - pygeos==0.14
    - PyJWT==2.8.0
    - pyparsing==3.1.1
    - pyproj==3.5.0
    - pystac==1.8.4
    - pystac-client==0.7.5
    - python-dateutil==2.8.2
    - python-dotenv==1.0.0
    - pytz==2023.3
    - PyYAML==6.0.1
    - rasterio==1.3.9
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - shapely==2.0.2
    - six==1.16.0
    - snuggs==1.4.7
    - sortedcontainers==2.4.0
    - stackstac==0.5.0
    - tblib==3.0.0
    - toolz==0.12.0
    - tornado==6.4
    - tqdm==4.66.1
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - utm==0.7.0
    - xarray==2023.1.0
    - xarray-spatial==0.3.7
    - xyzservices==2023.10.1
    - yarl==1.9.4
    - zarr==2.16.1
    - zict==3.0.0
