# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- group: EBIO-STATE-VG
- name: terraformDirectory
  value: $(Build.SourcesDirectory)/infra/terraform
- name: scriptsDirectory
  value: $(Build.SourcesDirectory)/.pipelines/infra/scripts

stages:
- stage: development
  jobs:
  - template: terraform-deploy-steps.yml
    parameters:
      environment: development
      location: $(LOCATION)
      resourceGroupName: $(RESOURCE_GROUP_NAME)
      storageAccountName: $(STORAGE_ACCOUNT_NAME)
      storageContainerName: $(CONTAINER_NAME)
      serviceConnection: $(AZURE_RM_SVC_CONNECTION)
