# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  terraformDirectory: $(Build.SourcesDirectory)/infra/terraform

steps:
- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform -version
  displayName: 'Display terraform version'

- script: |
    curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  displayName: 'Install tflint'

- script: |
    terraform fmt -recursive -diff -check
  workingDirectory: $(terraformDirectory)
  displayName: 'Check if terraform configuration files are correctly formatted'

- script: |
    tflint
  workingDirectory: $(terraformDirectory)
  displayName: 'Use tflint to detect potential issues'

- script: |
    terraform init -backend=false
    terraform validate
  workingDirectory: $(terraformDirectory)
  displayName: 'Validate terraform configuration files'
